import os

from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE")
OPENAI_API_VERSION = os.getenv("OPENAI_API_VERSION")
OPENAI_ENGINE_DEPLOYMENT_NAME = os.getenv("OPENAI_ENGINE_DEPLOYMENT_NAME")
OPENAI_ENGINE_MODEL_NAME = os.getenv("OPENAI_ENGINE_MODEL_NAME")
